version: '3'
jenkins:
    image: jenkins/jenkins:lts
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /Users/fangshifeng/Documents/jenkins_data:/var/jenkins_home 
    ports:
        - "8080:8080"
        - "50000:50000"
    user: root
    restart: "no"